### PR TITLE
Add sos2 costs 

### PR DESCRIPTION
**Pull request by simnh**
Hi I transferred the old sos stuff to this branch. I should work, but only for solvers that can handle sos-type constraints (e.g. gurobi). Right now the implementation works if you provide a list of tuples with base points to the investment.ep_costs attribute. (It does not work for storages so far,)

The same code would probably be needed for all nl-approx. costs (e.g. storage investment). Therefore it might be good to find a better place to drop the code. 

* [ ] Check functionality and interference with existing implementations
* [ ] Adapt documentation 
* [ ] Find the right location for the code
* [ ] Add an example
* [ ] Decide on API for investment
* [ ] Add check (for current implementation check if either scalar or list of tuples is passed) 

I will delete the other branch, hopefully this is a good starting point for you @jnnr !

### CODE REVIEW

**Comment by jnnr** [comment]
Hey simnh! Sorry for this late reply. And thanks for your code and this well structured introduction. I will dive into it as soon as I can find some time. As soon as I got something, I will let you know.

**Comment by uvchik** [comment]
@jnnr Is it still on your list?

**Comment by p-snft** [comment]
This is far from being merged. So, I released the requested reviewers and will postpone the feature request.

**Comment by uvchik** [comment]
@jnnr Is it still on your list?

**Comment by jnnr** [comment]
Thanks for asking, @uvchik. To be honest, I will not have time for this in the near future. To answer your question: This is rather not on my list at the moment.

**Comment by uvchik** [comment]
Everybody is free to reopen it or use the code for further development. By now it is only possible to define an offset for the invest costs (see #636).

**Pull request closed without merging**
