### PR TITLE
Features/max active flow count

### PR DESCRIPTION
**Pull request by p-snft**
This PR offers a generic solution to #567.

* [X] Implement first draft
* [X] When list of flows is given, usage keyword should not be enforced.
* [X] Add unit test for handing over list of Flows
* [x] Add proper example (can build upon the unit test)
* [x] Elaborate documentation
* [x] Add to whatsnew

### CODE REVIEW

**Comment by p-snft** [comment]
I added an example at [v0.3.x/flow_count_limit/flow_count_limit.py](https://github.com/oemof/oemof-examples/blob/features/max_active_flow_count/oemof_examples/oemof.solph/v0.3.x/flow_count_limit/flow_count_limit.py). However, at the moment, processing the results does not work. Any advice, @oemof-developer?

**Comment by p-snft** [comment]
I am unsure about the adjustment i made to oemof/outputlib/processing.py. Would you have a look, @oemof-developer?

**Comment by uvchik** [comment]
> I am unsure about the adjustment i made to oemof/outputlib/processing.py. Would you have a look, @oemof-developer?

See issue #630.

**Comment by uvchik** [comment]
We do use the numpy style for our docstrings, see https://oemof.readthedocs.io/en/latest/developing_oemof.html#docstrings

Would be nice to add an explaining sentence to the upper/lower parameter.

>Total actual counts after optimization can be retrieved calling the :attr:`om.oemof.solph.Model.$(constraint_name)_count()`.
Is it possible to find it in the results dictionary?

**Comment by p-snft** [comment]
Sorry for the wrong docstring format. I adjusted it.

**Comment by uvchik** [comment]
As we are about to publish v0.4.0 soon, you should change the base to dev to avoid confusing and complex conflicts.

**Comment by p-snft** [comment]
The decrease in coverage is resulting from my additional two lines in processing.py. However, I found that processing does not have real unit test but more of an integration test. What to do?

**Pull request merged**
