### PR TITLE
make BasicModel consider all constraint groups

### LINKED ISSUE #1002: BasicModel can ignore some constraint blocks in cellular models
When using the cellular modelling approach, the basic model considers only the constraint groups that are present in the first energy cell. This isn't a problem if all cells contain the same component types (that's why I didn't notice it earlier). But if, for example, only one cell contains a storage, the constraints of the storage are neglected.

### PR DESCRIPTION
**Pull request by lensum**
Closes #1002 by implementing a loop over all energy systems passed to the model class.

### CODE REVIEW

**Comment by jokochems** [comment]
Looks plausible and also like an important fix to introduce. Is it already finalized, @lensum?

**Comment by lensum** [comment]
Yes, it's ready to be merged (from my pov).

**Review by jokochems — APPROVED** [review]
Thanks for the fix, @lensum. Does make sense to me.

**Comment by lensum** [comment]
Thanks for the approval, @jokochems! Should I merge it or is it more "up to code" if someone else performs the merge?

**Pull request merged**
