### PR TITLE
Fix flow api build

### PR DESCRIPTION
**Pull request by joroeder**
* Describe your pull request as transparent as possible
  * [ ] Fixes the API build of the restructured modules
      * [ ] Flows
      * [ ] Buses
      * [ ] ...
  * [x] Updates the version numer to v0.5.0.dev0
      * [x] __init__
      * [x] setup.py
      * [x] VERSION
      * [x] docs/config.py
      * [x] whatnew (was already updated)

### CODE REVIEW

**Comment by joroeder** [comment]
To also build the block docstrings (that are not directly include as they are not in the init), it is necessary to include them "manually". This leads to ```oemof.solph.flows._flow.Flow```

Alternatively, we could add the Block classes to the init(s)? Is there anything against? And if it is just for buiding the API docu.

**Comment by joroeder** [comment]
An futher question is, should the API documentation be divided in non-experimental and experimental?

**Comment by p-snft** [comment]
Concerning blocks in the API reference: Strictly speaking, blocks are not part of the API. When just these two options are possible, I'd rather make the blocks part of the public API then displaying protected members. If possible, the block documentation should be inlined into the bus/ flow/ component classes docstring. (@jnnr, @gnn, didn't one of you try that?)

> An futher question is, should the API documentation be divided in non-experimental and experimental?

I'd suggest to have the documentation of an experimental bus/ link/ component within that category. The class documentation itself should state that it is experimental - optimally already in the headline (and thus in the table of contents).

**Comment by joroeder** [comment]
> 
> I'd suggest to have the documentation of an experimental bus/ link/ component within that category. The class documentation itself should state that it is experimental - optimally already in the headline (and thus in the table of contents).

I agree, that is also a fine solution. So, you would also not differentiate within the API indenture level and mark as "experimental"? By importing the user also needs to import from "experimental", right? So this should be clear anyway.

**Comment by joroeder** [comment]
> Concerning blocks in the API reference: Strictly speaking, blocks are not part of the API. When just these two options are possible, I'd rather make the blocks part of the public API then displaying protected members. If possible, the block documentation should be inlined into the bus/ flow/ component classes docstring. (@jnnr, @gnn, didn't one of you try that?)

As far as I remember from the last dev meeting, this is diffucult or not possible. But I agree this would be the most elegant solution. Providing the Bocks docstring (so the formulas and the tables with variables and parameter) only in the documentation (which we are doing for some components anyway) would be another alternative.

**Comment by jnnr** [comment]
> Concerning blocks in the API reference: Strictly speaking, blocks are not part of the API. When just these two options are possible, I'd rather make the blocks part of the public API then displaying protected members. If possible, the block documentation should be inlined into the bus/ flow/ component classes docstring. (@jnnr, @gnn, didn't one of you try that?)

There is something similar already, not inlining one docstring in another, but inlining a part of a docstring in the docs/usage.rst-file:

```
.. include:: ../src/oemof/solph/components/generic_chp.py
  :start-after: _GenericCHP-equations11:
  :end-before: """
```

**Comment by uvchik** [comment]
@jnnr Would be nice if there is something like this within the docstring. Any ideas?

The following workaround does not show the function as headline so that the docstring (only!) is displayed below the docstring of the Bus class. It looks like one docstring.

```python
oemof.solph.buses.Bus
---------------------

.. automodule:: oemof.solph.buses._bus
    :members: Bus
    :undoc-members:

.. automodule:: oemof.solph.buses._bus.BusBlock
    :members:
    :undoc-members:
```

grafik

Even though I am not sure if it is cleaner to link to the docstring of the Block class. On the other hand, not showing the API like in the example above makes clear that you should not use the API.

**Comment by joroeder** [comment]
Summary -- questions:
1) _ underscore in the API reference could be misleading for users.
2) divide into experimental or not. Decisions: no, as you need to import from experimental anyway

Further work is done in #772

**Comment by p-snft** [comment]
As "Further work is done in https://github.com/oemof/oemof-solph/pull/772", I will close this PR.

**Pull request closed without merging**
