### PR TITLE
Test for Features/add nonequidistant timeindex

### PR DESCRIPTION
**Pull request by c-koehl**
This pr relates to issue [#684](https://github.com/oemof/oemof-solph/issues/684).

A constraint test with comparing a lp file was added to the new feature of a nonequidistant timeindex.
I hope the tests validates the functionality. (e.g. the costs in the objective expression)

Additionally an unecessary import was deleted which can lead to circular imports.

### CODE REVIEW

**Comment by uvchik** [comment]
I think you did not use the most actual state of the dev branch. Please check if your remote dev branch is in line with the upstream dev branch. A merge might be difficult, but as you mostly just added code (not changed code) you can just save your code somewhere, update your dev and open a new PR. I think this would be the fastest way.

**Comment by joroeder** [comment]
> 
> 
> Everything seems fine. Nevertheless I had some issues adapting to the new structure of oemof. I could not run the nosetest command `nosetests -w "/path/to/oemof" --with-doctest`, because I received multiple import errors, e.g. in file solph/custom.py:
> 
> ```
> from oemof.network.network import Transformer as NetworkTransformer
> ModuleNotFoundError: No module named 'oemof.network'
> ```

``tox`` is the new test tool ([https://oemof-solph.readthedocs.io/en/v0.4.0/contributing.html#tests](https://oemof-solph.readthedocs.io/en/v0.4.0/contributing.html#tests)) you can run for example ```tox -e "clean, check, docs, py37"``` to specifiy the test run, e.g. just test with python 3.7 , or just the docs or the tests ...

**Comment by uvchik** [comment]
Shouldn't we add a component to the test where the constraints that differs with a non-equidistant time index (e.g. GenericStorage).

**Comment by c-koehl** [comment]
I deleted the import and use of sequence in helpers.py because it was leading to circular imports (in older versions, I don't know about the newer, flat ones) and I don't think it's necessary

**Comment by uvchik** [comment]
> I deleted the import and use of sequence in helpers.py because it was leading to circular imports (in older versions, I don't know about the newer, flat ones) and I don't think it's necessary

I agree, in your case it is always a list.

Could you please solve the merge conflicts.

**Review by p-snft — APPROVED** [review]
Looks very good and also answers questions I had about this feature.

**Comment by uvchik** [comment]
Thank you both for the test and the review. 

The most important thing is that you check the results for a storage in an energy system with a nonequidistant timeindex - especially the time sensitive results such as the loss rate. For example an example that leads in a  table that shows that the losses for a three hour time interval is three times higher than for a one hour interval.

After that we can merge it right away. The code base is fine.

**Comment by c-koehl** [comment]
It is not 3 times higher.
E.g. if you have a 0.1 loss rate per hour, after one hour the storage would have a capacity of 1 - 0.1 = 0.9 times it former capacity.
The capacity after 3h would be (1 - 0.1)  ^ 3 =  0.729 times it former capacity.
It is like the compound interest (zinseszins) formula

**Comment by uvchik** [comment]
> It is not 3 times higher.
> E.g. if you have a 0.1 loss rate per hour, after one hour the storage would have a capacity of 1 - 0.1 = 0.9 times its former capacity.
> The capacity after 3h would be (1 - 0.1) ^ 3 = 0.729 times its former capacity.
> It is like the compound interest (zinseszins) formula

Yes, I know. Sorry, I was not exact in my example. I just wanted to say that this has to be checked. If it works correctly for all these time sensible results I am fine with it.

**Comment by p-snft** [comment]
Continued in #851.

**Pull request closed without merging**
