### PR TITLE
Features/solph energy system methods

### PR DESCRIPTION
**Pull request by simnh**
Add some methods to the solph energy system to move functionality to the object according to the plan of #315 

* Related issues
#315

* TODOS: 

* [ ] Maybe some tests?
* [ ]  Examples

### CODE REVIEW

**Comment by uvchik** [comment]
I created a commit and reverted it afterwards, just to check if Travis still works in this PR. Sorry for the useless commits.

**Comment by jnnr** [comment]
Any comments on this PR? Shall we merge it before the release of v0.2.1 or take a bit more time for tests and examples?

**Comment by simnh** [comment]
I think we should not merge this right now. With the datapackage reader there are some additional changes to the energy system. I think the best way is to refactor this all together and add tests etc.

**Comment by uvchik** [comment]
If it is not urgent we could discuss the restructuring of `EnergySystem` and `Model` structure at the developer meeting in May (about two month from today) and merge it afterwards with v0.2.x or even 0.3 if necessary. 
@simnh Would this be okay for you or do need it sooner?

**Comment by simnh** [comment]
I think this would be enough for a release and final changes, but we would need it sooner as a working version on dev I think...

**Comment by uvchik** [comment]
I still like the idea. We should make a breakout group at the next developer meeting.

**Comment by uvchik** [comment]
I will present the general approach at the next meeting and if I do not find anybody who will support this idea I will close this issue.

**Comment by joroeder** [comment]
> 
> 
> I will present the general approach at the next meeting and if I do not find anybody who will support this idea I will close this issue.

Did you find somebody? ;)

**Comment by uvchik** [comment]
> Did you find somebody? ;)

I missed to put it on the agenda. I will try it again on the next user meeting :smile:

**Comment by p-snft** [comment]
As there is nobody working on this and all the work done is very old, probably a rewrite would be easier than adding to this PR. I will close this now.

**Pull request closed without merging**
