### PR TITLE
Allow  investment option for MILP via quadratic term transformation

### PR DESCRIPTION
**Pull request by simnh**
* Added a transformation to convert quadratic expression to linear ones
  in NonConvexBlock
* Adapted Flow API and Storage API accordingly

@mloenneberga : We talked about this feature for micro grid optimization. Maybe you can test with your examples. 

This does not work for storages so far, but could be implemented analogously. 

* [ ] Speed up Pmin/Pmax   model creation by replacing pyomo rule with for-loop and BuildAction
* [ ] Check functionality
* [ ] Adapt docstrings
* [ ] Think about internal naming and location.
* [ ] Check if this actually does not affect up/down, startup etc. stuff, but it should not so far...

### CODE REVIEW

**Comment by mloenneberga** [comment]
Great feature! Thanks for adding! I am currently really busy with my thesis, so it might take me a while to do so. Sorry.

**Comment by jnnr** [comment]
I changed the milestone to v0.2.2. Feel free to revert this if there is a chance to get the feature ready until Wednesday, 07.03.18

**Comment by simnh** [comment]
This was ment to be a draft for @mloenneberga, I do not know what the status is

**Comment by uvchik** [comment]
@mloenneberga Anything new?

**Comment by p-snft** [comment]
This is not in a state that is close to be merged. In fact, this feature request looks abandoned. So, I released the requested reviewers and postponed it (to the next release, so we do not forget about it).

**Comment by uvchik** [comment]
Anything new?

**Comment by simnh** [comment]
I think this can be closed...Once such a feature is required. We can create a new issue / PR..

**Comment by p-snft** [comment]
I'll close this, then.

**Pull request closed without merging**
