### PR TITLE
update docstrings of some classes in components.py

### PR DESCRIPTION
**Pull request by oakca**
Related issues #597 

- sets are removed from `GenericStorage` and `GenericInvestmentStorage`
- table is added to `GenericStorage` and  `OffsetTransformer` 
- some small changes for the length of the "===" in tables

### CODE REVIEW

**Comment by p-snft** [comment]
Looks good. When you think, it's ready to be merged, you can signify this by asking for a review.

**Comment by joroeder** [comment]
@oakca Thank you for your effort and initiative.
Is there a difference between the ..csv table syntax and the === table style? Or does it result in the same in readthedocs? For me, it was far more convenient to use the ...csv table syntax for writing the table. If the result is the same, in my opinion, everybody can choose the syntax he/she prefers. Of course, in the source code, the === syntax is more readable.

Are you planning to continue with that PR?

**Comment by jnnr** [comment]
> Of course, in the source code, the === syntax is more readable.

:+1:

**Comment by joroeder** [comment]
> 
> 
> > Of course, in the source code, the === syntax is more readable.
> 
> 👍

In #597 you can add your opinion ;)

**Comment by uvchik** [comment]
We could merge this into a feature branch to make it possible to finish the work.

@joroeder, @jnnr What do you think?

**Pull request merged**
