### PR TITLE
Integrate logo in sidebar and README

### LINKED ISSUE #786: Use solph logo
As we have a logo for solph (#745), we should start using it.

- [x] Documentation (PR: #806)
- [ ] Webpage (i.e. https://oemof.org/libraries/, issue: [oemof/issues/41](https://github.com/oemof/oemof/issues/41))

### PR DESCRIPTION
**Pull request by fwitte**
On top of that, amissing link in the installation instructions in the README is added.

# Tasks

- [x] The logo needs to be updated with the actual logo, currently there is still the first draft only @uvchik.
- [x] In the README the link to the logo should be static, else it cannot be displayed on PyPI (https://stackoverflow.com/questions/41983209/how-do-i-add-images-to-a-pypi-readme-that-works-on-github). We need to check, if the link changes after updating the image.
- [x] For some reason the `:ref:` identifier is not supported in the README, any ideas? 
- [x] Consider having some background color for sidebar logo

UPDATE:

* [Readthedocs](https://oemof-solph.readthedocs.io/en/features-integrate-solph-logo/)
* [README](https://github.com/oemof/oemof-solph/tree/features/integrate-solph-logo)
* [Logos](https://github.com/oemof/oemof-solph/tree/features/integrate-solph-logo/docs/_logo)

### CODE REVIEW

**Comment by uvchik** [comment]
The :ref: role is not allowed within a README, so I removed it.
https://packaging.python.org/en/latest/guides/making-a-pypi-friendly-readme/#validating-restructuredtext-markup

**Comment by fwitte** [comment]
Thank you for finishing @uvchik, Happy Holidays :)!

**Review by uvchik — APPROVED** [review]
Before Christmas :christmas_tree: :santa: I added some artwork and finished the logo issue. Feel free to use the logo whereever you want in the context of oemof.solph. Check the links below:

I am not sure about the fancy background adt Readthedocs (RTD), so feel free to change it. But I would prefer not to block this PR due to a discussion about the background of the logo at RTD. Please approve and discuss it in a new PR, because I also fixed the build on RTD.

* [Readthedocs](https://oemof-solph.readthedocs.io/en/features-integrate-solph-logo/)
* [README](https://github.com/oemof/oemof-solph/tree/features/integrate-solph-logo)
* [Logos](https://github.com/oemof/oemof-solph/tree/features/integrate-solph-logo/docs/_logo)

**Comment by uvchik** [comment]
> +1

Thank you @astrojuanlu for your instruction to solve the "setuptools" issue.

**Review by jokochems — APPROVED** [review]
Very nice, thank you!

**Pull request merged**
