### PR TITLE
Revise API and behaviour of fixed flows

### PR DESCRIPTION
**Pull request by jnnr**
Implements the changes discussed in #547.

The steps I took according to the discussion in the issue:
* [x] Rename `actual_value` to `fix`,
* [x] Write a test that fails when a value in the `fix` sequence >1 in investment mode,
* [x] Fix it by not building max constraint for fixed flows,
* [x] I did not remove 'fixed', but it does not have to be passed explicitly as it is set to True in the 
background when fix is passed. Is that ok so? And shall I remove the explicit passing of 'fixed' from the tests?

Open TODOs in the docs:
* [ ] Replace `actual_value` in the docs
* [ ] Explain in the docs that `fix`, `min` and `max` are relative to `nominal_value`
* [ ] Explain in the docs that `fix` can be larger than 1.  

Can you have a look @oemof/oemof-solph?

### CODE REVIEW

**Comment by p-snft** [comment]
I second @uvchik's comments but would be more strict: This is (also) meant to be a simplification. At the moment, setting `actual_value` has no effect if you do not also set `fixed` – this is unintuitive and may happen unnoticed. So, the name `fixed` is chosen so that you do not need redundant parameters.

Just closely related (but an easy fix within this PR): As `fix`, also `max` can be  >1. (I consider this very useful, please adjust the documentation an do not remove the feature.)

**Comment by uvchik** [comment]
> I second @uvchik's comments but would be more strict: This is (also) meant to be a simplification. At the moment, setting `actual_value` has no effect if you do not also set `fixed` – this is unintuitive and may happen unnoticed. So, the name `fixed` is chosen so that you do not need redundant parameters.

As I understand it, we already decided to remove the `fixed` attribute and to rename the `actual_value` attribute to `fix`.

I agree that it should be possible to set `max` and/or `fix` > 0, but if `max` and `fix` is not set, `max` is set to 1 by default (as shown in the code example above). You are still free to set `max` to 100 if you want.

**Comment by jnnr** [comment]
Thanks for your comments! I will continue working on this next week.

**Comment by uvchik** [comment]
Okay, I think the code should work now. We should create an example that produces wrong results on the dev-branch but correct results (renaming `actual_value` to `fix`) on this branch. @jnnr Could you do that?

I removed the `fixed` attribute. The new `fix` attribute is `None` by default and if it is not None the variable of the Flow will be fixed to this value. It is not allowed to set `fix` and (`max` or `min`) at the same time, because this makes no sense.

I do not know why codecov fails, I do not think that I added uncovered lines and coveralls is okay.

We do need to check the documentation. I renamed `actual_value` to `fix` but there still might be some occurrences of `fixed` or `fixed=True`.

**Comment by p-snft** [comment]
> We still have to adapt the documentation.

Thanks, I missed these few lost occurrences in my review. Should be removed now.

**Comment by uvchik** [comment]
Thank you for fixing that right away.

**Pull request merged**
