### PR TITLE
Revise docstring

### PR DESCRIPTION
**Pull request by uvchik**
[Post updated and edited by @jokochems on 10.11.2022]

The actual documentation of this PR: https://oemof-solph.readthedocs.io/en/docs-revise-docstrings/reference/

We have dozen of wrong references in our docstrings and some equations are unreadable. It is a lot of work for one person to fix all the docstrings but it is NOT so much work to fix one or two docstrings. So please help.

1. clone solph
2. checkout `docs/revise-docstrings`

Use `tox` to build the documentation and see the warnings.

1. Open your Python environment
2. Uninstall solph (if it is installed)
2. Use `pip install -e /your/path/oemof-solph` to install a modifiable version of solph
2. Move to your clone of the solph repository (`cd /your/path/oemof-solph`)
3. Install/update `tox`: `pip install tox --upgrade`
4. Use `tox -e docs` to build the documentation and see the warnings 
5. You will find the html-version of the docs in `/your/path/oemof-solph/dist/docs/index.html`

You want to help but you are unsure what to do? Write a comment or contact me. If there are many questions we could make a Q&A-WebCo. It is a good first contribution but we need the help of all contributors, so that it is less work for each person.

You can also join the chat to ask questions: https://matrix.to/#/#oemof.solph:matrix.org?via=matrix.org

Try to finish your work within one month after you assigned yourself.

I did not check all docstrings, so you do not have to do anything if everything is fine :exclamation: 

You should fix all failing references. References like `:py:attr:` will never work. You can use `:py:class:` or `:py:func` e.g.:
:py:class:`~oemof.solph.components.generic_storage.GenericStorageBlock`

The eqautions should be readable e.g. https://oemof-solph.readthedocs.io/en/latest/reference/oemof.solph.html#oemof.solph.components.offset_transformer.OffsetTransformerBlock

Everything else should be readable, look nice, and contain all needed information.

:red_circle: open
:large_orange_diamond: assigned
:heavy_check_mark: done

 * [x] bus.py (all) (@uvchik, June-3) :heavy_check_mark:
 * [x] flow.py (all)  (@uvchik, June-3) :heavy_check_mark:
 * [x] investment_flow.py (@uvchik, June-3) :heavy_check_mark:
 * [x] transformer.py (all) (@uvchik, June-3) :heavy_check_mark:
 * [x] non_convex_flow (@p-snft ) :heavy_check_mark:
 * [x] extraction_turbine_chp.py (@lensum) :heavy_check_mark:
 * [x] generic_chp.py (@jokochems ) heavy_check_mark:
 * [x] generic_storage.py (@jokochems, March-8/22) -> no need for changes :heavy_check_mark:
 * [x] offset_transformer.py (@jokochems) :heavy_check_mark:
 * [x] equate_variables.py (@jokochems) :heavy_check_mark:
 * [x] flow_count_limit.py (@jokochems) :heavy_check_mark:
 * [x] integral_limit.py (@jokochems) :heavy_check_mark:
 * [x] investment_limit.py (@jokochems) :heavy_check_mark:
 * [x] shared_limit.py (@jokochems) :heavy_check_mark:
 * [x] energy_system.py (@jokochems, March-8/22) -> no need for changes :heavy_check_mark:
 * [x] sink.py (@jokochems, March-8/22) :heavy_check_mark:
 * [x] source.py (@jokochems, March-8/22) :heavy_check_mark:
 * [x] groupings.py (@jokochems) :heavy_check_mark:
 * [x] helpers.py (@p-snft) :heavy_check_mark:
 * [x] models.py (@jokochems) :heavy_check_mark:
 * [x] options.py (@jokochems) :heavy_check_mark:
 * [x] plumbing.py (@p-snft) :heavy_check_mark:
 * [x] processing.py (@jokochems) :heavy_check_mark:
 * [x] views.py (@p-snft) :heavy_check_mark:
 * [ ] electrical_line.py () :red_circle: (-> experimental, not a blocker)
 * [x] generic_caes.py (@jokochems ) :heavy_check_mark:
 * [x] link.py (@p-snft) :heavy_check_mark:
 * [ ] piecewise_linear_transformer.py :large_orange_diamond: (@jnnr, June 3rd)  (-> experimental, not a blocker)
 * [x] sink_dsm.py (@jokochems) :heavy_check_mark:
 * [x] usage.rst (@p-snft) :heavy_check_mark:

### CODE REVIEW

**Comment by jokochems** [comment]
Thanks for the detailed "How to" description. Seems I cannot edit the message directly, but I could help with
* sink_dsm.py
* models.py
* options.py

**Comment by jokochems** [comment]
@uvchivk: Please refer to #775 for my share on this one. Thank you!

**Comment by uvchik** [comment]
When you merge #755 it will occur here. Perfect!

**Comment by jokochems** [comment]
Sorry for messing up the commit history, @uvchik Somehow, my black formatter was configured a tiny bit different which led to a failing black test / merge conflicts which I had to resolve. (I wonder that this hasn't appeared when I merged from my fork into this PR, though.) Anyways, it should be all fine now.

**Comment by jokochems** [comment]
I'm sorry, I looked into the `_generic_storage` module already a while ago and found it very well documented and no need to change anything here.

The changes to `timeindex` and `timeincrement` anyways change constraints. This should be included in the corresponding PR. In addition to that, we could make it explicit in the documentation, when storage level values are defined, i.e. before or after realising the flow - we had that discussion already.

**Comment by p-snft** [comment]
Not a docstring, but also documentation in usage.rst needs to be updated.

**Comment by p-snft** [comment]
* Everything that is missing is in experimental components.
* Doctest failed due to problem reaching external server (Error 403).
* Coverage didn't change as only docstings but no code segments were touched.

Ready for review.

**Review by p-snft — APPROVED** [review]
* Everything that is missing is in experimental components.
* Coverage change probably is wrong, as only docstings but no code segments were touched. (Number seems to jump between two values for the same code. One is a slight decrease, the other a slight increase.)

**Pull request merged**
