### PR TITLE
Release v0.4.5

### LINKED ISSUE #899: Release of v0.4.5
We want to release `oemof.solph` version 0.4.5 as this is needed for [`oemof.tabular`](https://github.com/oemof/oemof-tabular) release.
We would base v0.4.5 on branch [v0.4](https://github.com/oemof/oemof-solph/tree/v0.4).
Any objections?

### PR DESCRIPTION
**Pull request by henhuy**
Closes #899

### CODE REVIEW

**Comment by henhuy** [comment]
Tests are failing for py37 and py38 (also locally) with error message:
`py38: InterpreterNotFound: python3.8`
Tried solution from https://stackoverflow.com/a/68413752/5804947, but could not get it to work.
`py39` works fine though!

**Comment by p-snft** [comment]
I added two fixes. Now, the tests are failing because (additional) warnings are issued by external libraries, that were not present when the tests were designed. Are you able to fix those?

**Comment by henhuy** [comment]
> I added two fixes. Now, the tests are failing because (additional) warnings are issued by external libraries, that were not present when the tests were designed. Are you able to fix those? 

Thanks for the help! @p-snft 
We will take over!

**Comment by jnnr** [comment]
There seems to be cross-talk between the tests that fails the test_warnings. 
More precisely, the setting of `Node.registry = self.energysystem` in constraint_tests.py introduces an extra warning in tests_warnings.py, which fails the assertions about the length of the warning.

I found out by running the tests locally. If I only run pytest/test_warnings.py, it passes. If I run `pytest tests/constraint_tests tests/test_warnings.py`, it fails because the warning about Node.registry appears.

**Comment by p-snft** [comment]
I completely removed usage of `node.registry` in #867 (later included in #836).

**Comment by jnnr** [comment]
> I completely removed usage of `node.registry` in #867 (later included in #836). But I don't know if it's easily included n v0.4.

Would it make sense to merge `revision/remove_node_registry` into the release branch here?

**Comment by p-snft** [comment]
Unfortunately, ``revision/remove_node_registry` was forked from a branch containing the v0.5 structure. (In the end, it might be easier to upgrade your app to solph v0.5. In the end, updating from v0.4 to v0.5 should just mean changing some imports.)

**Comment by jnnr** [comment]
> (In the end, it might be easier to upgrade your app to solph v0.5. In the end, updating from v0.4 to v0.5 should just mean changing some imports.)

Yeah, I wonder! On the other hand, solph v0.5 needs adaptions to the new timeindex.

**Comment by p-snft** [comment]
The new timeindex can reproduce the old behaviour if you explicitly state that you want it to do so. Also, there is mainly the review for #877 missing before v0.5 can be released. (If you provide one, I can have a look at tabular. It needs to be updated at some point, anyway.)

**Comment by jnnr** [comment]
Sounds reasonable - it is better to move forward. I already opened a PR in tabular with adaptions to solph 0.5: https://github.com/oemof/oemof-tabular/pull/57

**Comment by jnnr** [comment]
With numpy 1.24, I get these test fails (numpy 1.23 works).
```
   FAILED tests/test_processing.py::TestParameterResult::test_parameter_with_node_view - ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (1, 2) + inhomogeneous part.
  FAILED tests/test_scripts/test_solph/test_connect_invest/test_connect_invest.py::test_connect_invest - ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (1, 2) + inhomogeneous part.
  FAILED tests/test_scripts/test_solph/test_storage_investment/test_storage_with_tuple_label.py::test_tuples_as_labels_example - ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (1, 2) + inhomogeneous part.
  FAILED tests/test_scripts/test_solph/test_variable_chp/test_variable_chp.py::test_variable_chp - ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (1, 2) + inhomogeneous part.
```

**Comment by jnnr** [comment]
@henhuy: I could fix the tests (see my last commits and post).
The remaining failing checks are coverage and black.
Can you have another look and help me getting this finished?

**Review by p-snft — APPROVED** [review]
I'm in favour of releasing this. At v0.4.4 has problems with up-to-date Numpy, this here is actually a real hotfix release.

**Comment by p-snft** [comment]
Codacy states that it did not analyse the branch.

**Comment by jnnr** [comment]
> I'm in favour of releasing this. At v0.4.4 has problems with up-to-date Numpy, this here is actually a real hotfix release.

Which problems with numpy do you mean? I constrained numpy < 1.24 here, too to fix 4 tests. I could adapt the tests to fix them, but I was not sure if there are other problems with numpy >= 1.24 that are not detected by the tests.

**Review by jnnr — APPROVED** [review]
Looks good! A what's-new-file is still missing, though.

**Comment by p-snft** [comment]
Also, don't forget the version number. Currently, it is "0.4.5.dev0" for the present branch.

**Comment by jnnr** [comment]
> Also, don't forget the version number. Currently, it is "0.4.5.dev0" for the present branch.

Yes, in these 4 locations: 
setup.py
VERSION
doc/conf.py
oemof/solph/__init__.py

**Comment by Bachibouzouk** [comment]
Would it be possible to include #895 in this release? Or is it to be included in 0.5.0 ?

**Comment by jnnr** [comment]
> Would it be possible to include #895 in this release? Or is it to be included in 0.5.0 ?

Please try to include it in  0.5.0 - 0.4.5 does not accept anything new.

**Comment by p-snft** [comment]
> Would it be possible to include #895 in this release? Or is it to be included in 0.5.0 ?

We moved to more frequent (pre-) releases. Note that there are an alpha and a beta release of v0.5.0. So,  I don't see why we should not make a (pre-) release just after #895 is merged.

**Pull request merged**
