### PR TITLE
Multi Period

### PR DESCRIPTION
**Pull request by simnh**
this introduces TIMEINDEX as a set (period,timestep) for flows.

### CODE REVIEW

**Comment by simnh** [comment]
Can you have a look here, and check if'ts ok for you. basically for now it's just internal handling, so for all current problems only the index should change inside the lp-files.

**Comment by ckaldemeyer** [comment]
> Can you have a look here, and check if'ts ok for you. basically for now it's just internal handling, so for all current problems only the index should change inside the lp-files.

Could you provide a minimal example for a multi-period usage? Or is it not working?

> I did not yet adapt CAES and GenericCHP

There are no tests so far ;-)

**Comment by simnh** [comment]
yeah because before I write test, provide an example and adapt existing test and fix all bugs, I like to now if the general idea  / direction of where the code is goiing is ok for you?

**Comment by ckaldemeyer** [comment]
> yeah because before I write test, provide an example and adapt existing test and fix all bugs, I like to now if the general idea / direction of where the code is goiing is ok for you?

As long as everything works I am fine. By having a quick look it looks good for me!

**Comment by simnh** [comment]
I won't have the time to do it for the next version. therefore I moved the milestone, to 'nice-to-have'

**Comment by p-snft** [comment]
Closed in favour of #750, which continues and expands what has been started here.

**Pull request closed without merging**
