### PR TITLE
Revise README

### PR DESCRIPTION
**Pull request by uvchik**
Revise the [README](https://github.com/oemof/oemof-solph/tree/docs/improve-readme) file:

 * [x] add new test badges
 * [x] remove Travis badge 
 * [ ] add logo as in oemof/oemof
 * [x] fix links to oemof/oemof documentation
 * [ ] add logo to readthedocs

### CODE REVIEW

**Comment by uvchik** [comment]
I just inserted the logo from #745 even though no decision was taken. It shows the overall layout and the logo can be replaced afterwards if the decision was taken,

**Comment by uvchik** [comment]
I remove the logo to make it possible to merge this PR because it fixes the broken tests.

**Comment by uvchik** [comment]
I fixed broken references and added the base for the new logo. See #745. We can exchange the logos Once we took a decision.

Can we merge this soon to fix the failing test.

**Review by p-snft — COMMENTED** [review]
I am not sure whether we should introduce a temporary logo that we know we will replace rather soon. Maybe wait until we decide for one.

**Comment by uvchik** [comment]
I added the badges and fixed the link. As I wrote above I will NOT add the logo until the decision was taken.

**Pull request merged**
